"""create-fib-entry

Revision ID: 40b83d85c278
Revises: 
Create Date: 2021-08-21 04:32:08.850326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b83d85c278'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fib_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_number', sa.Integer(), nullable=True),
    sa.Column('calculated_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fib_entries')
    # ### end Alembic commands ###
